[default]
LOG_LEVEL = "WARN"
LOG_DIR = "./tests/log"
DATA_DIR = "./tests/data"
CONF_FILE = "./tests/conf"
REPORT_DIR = "./tests/report"

[production]
LOG_LEVEL = "ERROR"
BASE_DIR = "$HOME/.local/share/spt-reporting"
LOG_DIR = "env:BASE_DIR/log"
DATA_DIR = "env:BASE_DIR/data"
CONF_FILE = "$HOME/.config/spt_reporting.toml"
REPORT_DIR = "env:BASE_DIR/report"

[testing]
LOG_LEVEL = "DEBUG"
LOG_DIR = "./tests/log"
DATA_DIR = "./tests/data"
CONF_FILE = "./tests/conf"
REPORT_DIR = "./tests/report"
